[TOP-LEVEL PARAMETERS]
simulation_mode = FULLY_INTRINSIC_CGP
base_config = data/default_config.ini

[FITNESS PARAMETERS]
# only pulse count supported for now
fitness_func = TOLERANT_PULSE_COUNT
desired_freq = 10000000

[GA PARAMETERS]
population_size = 50
mutation_probability = 0.01
crossover_probability = 0
elitism_fraction = 0.1
selection = FIT_PROP_SEL
diversity_measure = HAMMING_DIST
random_injection = 0.0

[INITIALIZATION PARAMETERS]
init_mode = CLONE_SEED_MUTATE
# RANDOMIZE_UNTIL not supported yet

[STOPPING CONDITION PARAMETERS]
generations = 100
target_fitness = IGNORE

[PLOTTING PARAMETERS]
# not available in container; copy workspace to host and manually run PlotEvolutionLive
launch_plots = false


[HARDWARE PARAMETERS]
# set routing to ALL to remove all row restraints, i've had the best results with it
routing = MOORE
accessed_columns = 14,15,17,36,37,38,39,40,41,42,43,44,45

